language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
#  - "3.7-dev"  # 3.7 development branch, no tf there
# command to install dependencies
install:
  - python setup.py install
  - pip install scipy scikit-learn
# command to run tests
script:
  - nosetests test.py
